### ISSUE TITLE
JUNIPER-SMI breaks LLD.py

### ISSUE THREAD

**Issue by xaintys** [Prototype-X/Zabbix-Template-Juniper-MX-BGP4-ipv4-ipv6#9]
Hi,

There is a bug when you install mib called JUNIPER-SMI the script LLD.py won't work properly anymore. He won't translate ip addresses from hex to decimal.

Regards.

**Comment by lukaslhs** [comment]
Same here.

`Traceback (most recent call last):
  File "./LLD.py", line 125, in <module>
    main()
  File "./LLD.py", line 118, in main
    elem_dict[macro] = all_oid_dict[macro][key]
KeyError: '0'
`
